Add rekey function
CQCL/portgraph pull request #44
Opened 2023-05-15 13:35 UTC by lmondada

I think this would be a useful addition to `SecondaryMap`, covering most common use cases
of `rekey` callback functions.

2023-05-15 14:03 UTC, aborgna-q requested changes

2023-05-15 14:03 UTC, aborgna-q commented on src/secondary.rs
> +            self[new] = val;
This needs to call `resize_for_get_mut` first, since `new` may not have been allocated.
Check the `swap` function, which does something similar.

2023-05-15 14:04 UTC, aborgna-q commented on src/secondary.rs
> +            self[new] = val;
(Maybe move put this and `swap` together, for readability)

2023-05-16 07:31 UTC, lmondada commented
Your comment made me realise that actually `resize_for_get_mut` was called implicitly by `Self::get_mut`. This meant that the `self.data` container would be resized even when e.g. `self.data` was empty and a no-op would suffice. I've changed the code to only resize when necessary.

There is one edge case in which we are resizing even though it is not strictly necessary: when `old.into() < self.data.len()` but `old` is actually `V::Default`. The only way to catch that case would be to add the `V: Eq` bound I think, so I prefered leaving it as it is.

Cheers!

2023-05-16 08:31 UTC, aborgna-q approved these changes
Maybe it could be clearer with a big `if` on `old.into() < self.data.len()`, but lgmt

2023-05-16 09:41 UTC, lmondada commented
You're right this is clearer.

2023-05-16 09:45 UTC, merged