Generic trait for SecondaryMaps
CQCL/portgraph pull request #51
Opened 2023-05-25 13:03 UTC by aborgna-q

This is a big breaking change that will give us more flexibility when managing secondary data on a portgraph.

It adds a `SecondaryMap` trait that encapsulates the common interfaces we use when managing node and port data.
We can then implement that trait on different structures like the old `SecondaryMap` (now renamed `UnmanagedMap`), bit vec for boolean storage, and any {Hash,BTree}{Set,Map}. This closes #46.

With this, we can add a `Map` generic parameter to `DominatorTree` and `TopoSort` that lets us use more efficient structures when we do not traverse the full graph. This closes #31.

Also:
- Renames the old SecondaryMap struct as "UnmanagedMap".
- Implements SecondaryMap for BitVec.
- Uses the trait in Dominators and TopoSort to avoid wasting memory when doing partial traversals.

There's a TODO to implement SecondaryMap for sparse containers (hash and BTree), but those can be done in another non-breaking PR.

2023-05-25 13:04 UTC, aborgna-q commented
@zrho You may have comments on this.

2023-05-30 13:34 UTC, ss2165 requested changes
I believe there's a bug in BitVec implementation but otherwise looks mostly ok

2023-05-30 14:32 UTC, aborgna-q commented on src/algorithms/toposort.rs
> +                visited_ports.set(port, true);
Yes, that is part of the definition of `SecondaryMap`:

```
/// A map from keys to values that does not manage it's indices.
///
/// Querying a key that has not been set returns a default value.
```

(and `default_value` returns `false` for BitVec)

2023-05-30 14:36 UTC, zrho commented on src/secondary.rs
> +    /// capacity of the secondary map in line with the size of the key space.
It would be nice if it guaranteed *not* to resize in cases that the data is not present.

2023-05-30 14:38 UTC, aborgna-q commented on src/secondary.rs
> +    /// capacity of the secondary map in line with the size of the key space.
Yes, that comment came from the `set` method and it shouldn't be part of the `take` definition.

2023-05-30 14:47 UTC, zrho commented
Looks good to me.
1. The concept of capacity might be a bit confusing when the key is generic, especially when reducing capacity cuts things off; perhaps it could be explained that it is intended to be used with keys that are convertible with numbers? 
2. `UnmanagedMap` could perhaps be `UnmanagedDenseMap` to emphasize that it is a dense storage?

2023-05-30 14:54 UTC, aborgna-q commented
> 1. The concept of capacity might be a bit confusing when the key is generic, especially when reducing capacity cuts things off; perhaps it could be explained that it is intended to be used with keys that are convertible with numbers?

Yes, perhaps `shrink_to` should be left for the concrete `impl`s instead of being part of the trait.

> 2. `UnmanagedMap` could perhaps be `UnmanagedDenseMap` to emphasize that it is a dense storage?

👍

2023-05-30 15:20 UTC, aborgna-q commented on src/algorithms/toposort.rs
> +                visited_ports.set(port, true);
Added the check to toposort. If the default value is `true` it initializes everything (and states so in the docs).

2023-05-30 15:21 UTC, zrho approved these changes

2023-05-30 15:24 UTC, merged