Fix UB in secondary map, and more bugs
CQCL/portgraph pull request #7
Opened 2023-03-13 12:15 UTC by aborgna-q

The `get_disjoint_mut` fn had UB, but thankfully miri caught it (the test was showing weird behaviour).
Also `ensures_capacity` was a no-op.

Adds tests and docs to everything

2023-03-13 12:22 UTC, aborgna-q commented
I used a new function from #4 in the examples, so the tests will pass once that is merged.

2023-03-14 11:25 UTC, ss2165 requested changes
main thing is the API renaming suggestion, the rest are just typos I think

2023-03-14 11:25 UTC, ss2165 commented on src/secondary.rs
> +//! // The map do not track item removals, but the user can shrink the map manually.
```suggestion
//! // The map does not track item removals, but the user can shrink the map manually.
```

2023-03-14 11:25 UTC, ss2165 commented on src/hierarchy.rs
> +        assert!(hierarchy.attach_first(root, child2).is_err());
is this a cycle error? if so can we check for it explicitly? (with an `assert_eq`)

2023-03-14 11:25 UTC, ss2165 commented on src/weights.rs
> +//! // The map do not track item removals, but the user can shrink the map manually.
```suggestion
//! // The map does not track item removals, but the user can shrink the map manually.
```

2023-03-14 11:27 UTC, aborgna-q commented on src/hierarchy.rs
> +        hierarchy.attach_first(child0, root).unwrap();
I agree, I'll change them

2023-03-14 15:43 UTC, merged